[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
  lovyan03/LovyanGFX
  adafruit/Adafruit NeoPixel @ ^1.12.0

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DNCOS_PIN_PROFILE_SIM=0
  -DNCOS_SIM_MODE=0

[env:esp32s3_sim]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps =
  lovyan03/LovyanGFX
  adafruit/Adafruit NeoPixel @ ^1.12.0

build_type = release
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DNCOS_PIN_PROFILE_SIM=1
  -DNCOS_SIM_MODE=1
  -DNCOS_SIM_ULTRA=1
  -DLOG_LOCAL_LEVEL=0
