#pragma once

enum class EventType {
  None = 0,
  Any,
  BootStarted,
  BootComplete,
  Heartbeat,
  FaceFrameRendered,
  CameraFrameSampled,
  EVT_VISION_SNAPSHOT,
  EVT_VISION_MOTION,
  EVT_VISION_DARK,
  EVT_TOUCH,
  EVT_SHAKE,
  EVT_TILT,
  EVT_FALL,
  EVT_IDLE,
  EVT_VOICE_START,
  EVT_VOICE_ACTIVITY,
  EVT_VOICE_END,
  EVT_INTENT_DETECTED,
  EVT_DIALOGUE_RESPONSE,
  EVT_CLOUD_REQUEST,
  EVT_CLOUD_RESPONSE,
  EVT_CLOUD_FALLBACK,
  EVT_POWER_STATUS,
  EVT_POWER_MODE_CHANGED,
  EVT_CHARGING_STATE_CHANGED,
  EVT_ATTENTION_CHANGED,
  EVT_GESTURE_PLAYED,
  EVT_ROUTINE_STATE_CHANGED,
  EVT_MOOD_CHANGED,
  EVT_ENGAGEMENT_CHANGED,
  EVT_PREFERENCE_UPDATED,
  EVT_PERSONA_UPDATED,
  EVT_AFFINITY_CHANGED,
  EVT_MOTION_POSE_APPLIED,
  EVT_EMOTION_CHANGED,
  EVT_BEHAVIOR_ACTION
};

enum class EventSource {
  Unknown = 0,
  System,
  FaceService,
  VisionService,
  SensorService,
  MotionService,
  EmotionService,
  InteractionService,
  BehaviorService,
  VoiceService,
  IntentEngine,
  DialogueEngine,
  CloudRouter,
  PowerService,
  AttentionService,
  GazeService,
  GestureService,
  MotionSyncService,
  RoutineService,
  MoodService,
  EngagementService,
  PreferenceMemoryService,
  PersonaService,
  AffinityService
};
